//*****************************************************************************************
/// \copyright (c) 2016-2026 Benjamin Wassermann
// ---------------------------------------------------------------------------------------
// This file is part of LineExtraction and is licensed under the MIT License.
// See the LICENSE file at the project root for more information.
//*****************************************************************************************
/// @file preset_store.hpp
/// @brief Store and retrieve optimized detector parameter presets from JSON.
///
/// Loads presets generated by `optimize_presets.py` and provides lookup
/// by detector name and preset profile (fast / balanced / accurate).
///
/// JSON schema (input):
/// @code{json}
/// {
///   "metadata": { ... },
///   "detectors": {
///     "LsdCC": {
///       "fast":     { "params": {"nms_th_low": 0.01, ...}, "score": 0.85 },
///       "balanced": { "params": {...}, "score": 0.90 },
///       "accurate": { "params": {...}, "score": 0.78 }
///     },
///     ...
///   }
/// }
/// @endcode

#pragma once

#include <algorithm/detector_profile.hpp>
#include <algorithm/search_strategy.hpp>
#include <utility/value.hpp>

#include <map>
#include <stdexcept>
#include <string>
#include <vector>

namespace lsfm {

/// @brief Store of optimized detector parameter presets loaded from JSON.
///
/// Typically the JSON is generated by `optimize_presets.py` which runs
/// random search over detector parameters and records the best configuration
/// for three profiles: **fast** (Precision), **balanced** (F1), and
/// **accurate** (Recall).
///
/// @example
/// @code{cpp}
/// // Load presets from file
/// PresetStore store("resources/presets/lsd_presets.json");
/// auto params = store.get(DetectorId::LSD_CC, "balanced");
/// detector.value(params);
///
/// // Check available presets
/// for (const auto& name : store.preset_names()) {
///   std::cout << name << "\n";
/// }
/// @endcode
class PresetStore {
 public:
  /// @brief Default preset profile names generated by optimize_presets.py.
  static constexpr const char* FAST = "fast";
  static constexpr const char* BALANCED = "balanced";
  static constexpr const char* ACCURATE = "accurate";

  /// @brief Construct an empty preset store.
  PresetStore() = default;

  /// @brief Load presets from a JSON file.
  /// @param json_path Path to the presets JSON file.
  /// @throws std::runtime_error if the file cannot be read or parsed.
  explicit PresetStore(const std::string& json_path);

  /// @brief Parse presets from a JSON string.
  /// @param json_content JSON content as a string.
  /// @return Populated PresetStore.
  /// @throws std::runtime_error if the JSON is malformed.
  static PresetStore from_string(const std::string& json_content);

  /// @brief Get parameter configuration for a detector and preset.
  /// @param detector Detector identifier.
  /// @param preset_name Preset profile name (e.g. "fast", "balanced", "accurate").
  /// @return Parameter configuration suitable for ValueManager::value().
  /// @throws std::out_of_range if detector or preset not found.
  ParamConfig get(DetectorId detector, const std::string& preset_name) const;

  /// @brief Get parameter configuration by detector name string.
  /// @param detector_name Detector name (e.g. "LsdCC").
  /// @param preset_name Preset profile name.
  /// @return Parameter configuration.
  /// @throws std::out_of_range if detector or preset not found.
  /// @throws std::invalid_argument if detector name is not recognized.
  ParamConfig get(const std::string& detector_name, const std::string& preset_name) const;

  /// @brief Get the optimization score for a detector preset.
  /// @param detector Detector identifier.
  /// @param preset_name Preset profile name.
  /// @return Score value (0–1, higher is better).
  /// @throws std::out_of_range if detector or preset not found.
  double score(DetectorId detector, const std::string& preset_name) const;

  /// @brief Get the optimization score by detector name string.
  /// @param detector_name Detector name.
  /// @param preset_name Preset profile name.
  /// @return Score value.
  /// @throws std::out_of_range if not found.
  double score(const std::string& detector_name, const std::string& preset_name) const;

  /// @brief Check whether a preset exists for the given detector.
  /// @param detector Detector identifier.
  /// @param preset_name Preset profile name.
  /// @return True if the preset exists.
  bool has(DetectorId detector, const std::string& preset_name) const;

  /// @brief Check whether a preset exists by detector name string.
  /// @param detector_name Detector name.
  /// @param preset_name Preset profile name.
  /// @return True if the preset exists.
  bool has(const std::string& detector_name, const std::string& preset_name) const;

  /// @brief Get all preset profile names present in the store.
  ///
  /// Returns the union of all preset names across all detectors.
  ///
  /// @return Sorted vector of unique preset names.
  std::vector<std::string> preset_names() const;

  /// @brief Get all detector names that have presets in the store.
  /// @return Sorted vector of detector name strings.
  std::vector<std::string> detector_names() const;

  /// @brief Check whether the store is empty.
  /// @return True if no presets are loaded.
  bool empty() const { return store_.empty(); }

  /// @brief Get the number of detectors with presets.
  /// @return Number of detectors.
  std::size_t num_detectors() const { return store_.size(); }

  /// @brief Apply a preset to a ValueManager-based detector.
  ///
  /// Convenience method combining get() + ValueManager::value().
  ///
  /// @param vm ValueManager-based detector to configure.
  /// @param detector Detector identifier.
  /// @param preset_name Preset profile name.
  /// @throws std::out_of_range if detector or preset not found.
  void apply(ValueManager& vm, DetectorId detector, const std::string& preset_name) const;

  /// @brief Apply a preset by detector name string.
  /// @param vm ValueManager-based detector to configure.
  /// @param detector_name Detector name.
  /// @param preset_name Preset profile name.
  void apply(ValueManager& vm, const std::string& detector_name, const std::string& preset_name) const;

 private:
  /// @brief A single preset entry: parameters + optimization score.
  struct PresetEntry {
    ParamConfig params{};  ///< Optimized parameter values.
    double score = 0.0;    ///< Optimization score (0–1).
  };

  /// @brief Parse JSON content into the internal store.
  /// @param json_content JSON string to parse.
  void parse(const std::string& json_content);

  /// @brief Internal lookup by detector name.
  /// @param detector_name Detector name.
  /// @param preset_name Preset profile name.
  /// @return Reference to the preset entry.
  /// @throws std::out_of_range if not found.
  const PresetEntry& lookup(const std::string& detector_name, const std::string& preset_name) const;

  /// @brief Mapping: detector_name -> preset_name -> PresetEntry.
  std::map<std::string, std::map<std::string, PresetEntry>> store_{};
};

}  // namespace lsfm
