#!/bin/sh
set -e

writeError() {
    if [ $# -lt 1 ] || [ $# -gt 2 ] ; then
        echo -e "\e[0;31mERROR: Wrong number of parameters passed to writeError" 1>&2
        echo -e "\e[m" 1>&2
        exit 1
    fi
    echo "\e[0;31mERROR: $1" 1>&2
    echo "\e[m" 1>&2
    exit 1
}

Usage="
Installs all apt packages in given apt list txt file that looks like the following:

pip             \`# comment1 \`
libgtest-dev    \`# comment2 \`

Parameters:
    -v/--verbose    verbose run
    -h/--help       display this help message
    -f/--file       apt list txt file
"

if [ "$(id -u)" -ne 0 ]; then
    writeError "Please run this script as root."
fi

while [ $# -gt 0 ]; do
case $1 in
    -v|--verbose)
        set -x
        shift
        ;;
    -h|--help)
        echo $Usage
        shift
        ;;
    -f|--file)
        if [ -z ${2+x} ]; then
            writeError "No value given for parameter -f|--file"
        fi
        file_path="$2"
        eval 'if [ ! -f $file_path ]; then writeError "File does not exist!"; fi'
        shift
        shift
        ;;
    *)
        writeError "Unknown option $1"
        exit 1
esac
done


# sed 's/`.*`//g' deletes everything between ` and `. E.g. pip `# reason why to install pip` --> pip
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y $(cat $file_path  | sed 's/`.*`//g' | tr '\n' ' ')
